server {
  listen 80;
  root /usr/share/nginx/html;
  location /api/ { proxy_pass http://stock_app:4000/; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $remote_addr; proxy_set_header Host $host; client_max_body_size 21m; }
  location = /stock-sw.js { add_header Cache-Control "no-cache"; }
  location / { try_files $uri $uri/ /index.html; }
}
